export const getInitialVideoData = () => [
  {
    id: 1,
    title: "Story 1",
    src: "/src/assets/1.mp3",
    duration: 0, // will be set when loaded
    watched: false,
    watchedPercentage: 0,
    lastPlayedTime: 0,
  },
  // Add similar objects for all 6 videos
  {
    id: 2,
    title: "Story 2",
    src: "/src/assets/2.mp3",
    duration: 0,
    watched: false,
    watchedPercentage: 0,
    lastPlayedTime: 0,
  },
  {
    id: 3,
    title: "Story 3",
    src: "/src/assets/3.mp3",
    duration: 0,
    watched: false,
    watchedPercentage: 0,
    lastPlayedTime: 0,
  },
  {
    id: 4,
    title: "Story 4",
    src: "/src/assets/4.mp3",
    duration: 0,
    watched: false,
    watchedPercentage: 0,
    lastPlayedTime: 0,
  },
  {
    id: 5,
    title: "Story 5",
    src: "/src/assets/5.mp3",
    duration: 0,
    watched: false,
    watchedPercentage: 0,
    lastPlayedTime: 0,
  },
  {
    id: 6,
    title: "Story 6",
    src: "/src/assets/6.mp3",
    duration: 0,
    watched: false,
    watchedPercentage: 0,
    lastPlayedTime: 0,
  },
  {
    id: 7,
    title: "Story 7",
    src: "/src/assets/7.mp3",
    duration: 0,
    watched: false,
    watchedPercentage: 0,
    lastPlayedTime: 0,
  },
  {
    id: 8,
    title: "Story 8",
    src: "/src/assets/8.mp3",
    duration: 0,
    watched: false,
    watchedPercentage: 0,
    lastPlayedTime: 0,
  },
  {
    id: 9,
    title: "Story 9",
    src: "/src/assets/9.mp3",
    duration: 0,
    watched: false,
    watchedPercentage: 0,
    lastPlayedTime: 0,
  },
  {
    id: 10,
    title: "Story 10",
    src: "/src/assets/10.mp3",
    duration: 0,
    watched: false,
    watchedPercentage: 0,
    lastPlayedTime: 0,
  },
  {
    id: 11,
    title: "Story 2",
    src: "/src/assets/11.mp3",
    duration: 0,
    watched: false,
    watchedPercentage: 0,
    lastPlayedTime: 0,
  },
  {
    id: 12,
    title: "Story 12",
    src: "/src/assets/12.mp3",
    duration: 0,
    watched: false,
    watchedPercentage: 0,
    lastPlayedTime: 0,
  },
];
